server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  messages:
    encoding: UTF-8

scheduler:
  payment:
    cron: "0/10 * * * * *"
  card:
    expire:
      cron: "0 0 0 * * *"
  account:
    expire:
      cron: "0 0 0 * * *"

payment:
  limits:
    card-min-balance: 10
    account-min-balance: 5
    monthly-limit: 100
    card-limit: 2
    account-limit: 3
    external-commission-rate: 0.02
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD}
